<a href="https://colab.research.google.com/github/NeoBro34/AI-Engineering/blob/main/Pandas__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-DARS: Pandas — Ma'lumotni jadvalga sol
## Endi NumPy massivlarimizni real jadvalga aylantiramiz.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# O'tgan darsdan ma'lumotlar

kunlar = ["Du", "Se", "Cho", "Pa", "Ju", "Sha", "Ya"]
sotuv  = [1_200_000, 980_000, 1_450_000, 870_000, 1_600_000, 2_100_000, 1_350_000]
mijozlar = [45, 38, 52, 31, 60, 87, 49]
harorat  = [22, 25, 19, 28, 31, 27, 24]

# DataFrame yaratish - bu bizning "jadvalimiz"
df = pd.DataFrame({
    "Kun"      : kunlar,
    "Sotuv"    : sotuv,
    "Mijozlar" : mijozlar,
    "Harorat"  : harorat
})

print(df)

   Kun    Sotuv  Mijozlar  Harorat
0   Du  1200000        45       22
1   Se   980000        38       25
2  Cho  1450000        52       19
3   Pa   870000        31       28
4   Ju  1600000        60       31
5  Sha  2100000        87       27
6   Ya  1350000        49       24

## Umumiy ma'lumot

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Kun       7 non-null      object
 1   Sotuv     7 non-null      int64
 2   Mijozlar  7 non-null      int64
 3   Harorat   7 non-null      int64
dtypes: int64(3), object(1)
memory usage: 356.0+ bytes

              Sotuv   Mijozlar    Harorat
count  7.000000e+00   7.000000   7.000000
mean   1.364286e+06  51.714286  25.142857
std    4.129914e+05  18.181623   3.976119
min    8.700000e+05  31.000000  19.000000
25%    1.090000e+06  41.500000  23.000000
50%    1.350000e+06  49.000000  25.000000
75%    1.525000e+06  56.000000  27.500000
max    2.100000e+06  87.000000  31.000000

## Ustunni tanlash

In [20]:
df["Kun"]         # bir ustun → Series

0     Du
1     Se
2    Cho
3     Pa
4     Ju
5    Sha
6     Ya
Name: Kun, dtype: object

In [19]:
df[["Kun", "Sotuv"]]  # bir nechta ustun → DataFrame

   Kun    Sotuv
0   Du  1200000
1   Se   980000
2  Cho  1450000
3   Pa   870000
4   Ju  1600000
5  Sha  2100000
6   Ya  1350000

# Qatorni tanlash

In [21]:
df.iloc[0] # 0-indeks (Dushanba)

Kun              Du
Sotuv       1200000
Mijozlar         45
Harorat          22
Name: 0, dtype: object

In [22]:
df.iloc[-1] # oxirgi qator (Yakshanba)

Kun              Ya
Sotuv       1350000
Mijozlar         49
Harorat          24
Name: 6, dtype: object

In [23]:
df.iloc[2:5] # 2 dan 4 gacha

   Kun    Sotuv  Mijozlar  Harorat
2  Cho  1450000        52       19
3   Pa   870000        31       28
4   Ju  1600000        60       31

# Yangi ustun qo'shish

In [25]:
df["Mijoz_boshiga"] = df["Sotuv"] / df["Mijozlar"]

print(df)

   Kun    Sotuv  Mijozlar  Harorat  Mijoz_boshiga
0   Du  1200000        45       22   26666.666667
1   Se   980000        38       25   25789.473684
2  Cho  1450000        52       19   27884.615385
3   Pa   870000        31       28   28064.516129
4   Ju  1600000        60       31   26666.666667
5  Sha  2100000        87       27   24137.931034
6   Ya  1350000        49       24   27551.020408

In [30]:
df["Mijoz_boshiga"] = df["Mijoz_boshiga"].round()

print(df)

   Kun    Sotuv  Mijozlar  Harorat  Mijoz_boshiga
0   Du  1200000        45       22        26667.0
1   Se   980000        38       25        25789.0
2  Cho  1450000        52       19        27885.0
3   Pa   870000        31       28        28065.0
4   Ju  1600000        60       31        26667.0
5  Sha  2100000        87       27        24138.0
6   Ya  1350000        49       24        27551.0

In [37]:
# Kun "yaxshimi yoki yo'q" - o'rtachadan yuqorimi
ortacha = df["Sotuv"].mean()
df["Yaxshi_kun"] = df["Sotuv"] > ortacha

df["Yaxshi_kun"] = df["Yaxshi_kun"].replace({
    True: "Yaxshi",
    False: "Yomon"
})

print(df)

   Kun    Sotuv  Mijozlar  Harorat  Mijoz_boshiga Yaxshi_kun
0   Du  1200000        45       22        26667.0      Yomon
1   Se   980000        38       25        25789.0      Yomon
2  Cho  1450000        52       19        27885.0     Yaxshi
3   Pa   870000        31       28        28065.0      Yomon
4   Ju  1600000        60       31        26667.0     Yaxshi
5  Sha  2100000        87       27        24138.0     Yaxshi
6   Ya  1350000        49       24        27551.0      Yomon

# Groupby — Guruhlash

In [38]:
# Yaxshi va yomon kunlarni solishtir
df.groupby("Yaxshi_kun")["Sotuv"].mean()

Yaxshi_kun
Yaxshi    1.716667e+06
Yomon     1.100000e+06
Name: Sotuv, dtype: float64

# Vazifa
  ## Quyidagilarni qilamiz:

  * 1. df dan faqat Shanba va Yakshanba qatorlarini chiqar (iloc yoki shart bilan)

  * 2. Yangi ustun qo'sh: "Sotuv_darajasi"
    - Sotuv > 1_500_000 bo'lsa → "Yuqori"
    - Sotuv > 1_000_000 bo'lsa → "O'rta"
    - Qolganlar          → "Past"
    - Maslahat: np.select() yoki df["ustun"].apply() ishlatib ko'r

  * 3. Har bir "Sotuv_darajasi" guruhida
    - nechta kun borligini hisобла
    - Maslahat: .value_counts()

  ## Bonus savol: iloc va loc farqi nima?

In [52]:
# Faqat Shanba va Yakshanba kunlar
df.loc[5:6]

   Kun    Sotuv  Mijozlar  Harorat  Mijoz_boshiga Yaxshi_kun
5  Sha  2100000        87       27        24138.0     Yaxshi
6   Ya  1350000        49       24        27551.0      Yomon

In [54]:
# Yangi ustun: "Sotuv_darajasi"

natija = [
    df["Sotuv"] >= 1_500_000,
    df["Sotuv"] >= 1_000_000,
]

daraja = ["Yuqori", "O'rta"]


df["Sotuv_darajasi"] = np.select(
    natija,
    daraja,
    default="Past"
)

print(df)

   Kun    Sotuv  Mijozlar  Harorat  Mijoz_boshiga Yaxshi_kun Sotuv_darajasi
0   Du  1200000        45       22        26667.0      Yomon          O'rta
1   Se   980000        38       25        25789.0      Yomon           Past
2  Cho  1450000        52       19        27885.0     Yaxshi          O'rta
3   Pa   870000        31       28        28065.0      Yomon           Past
4   Ju  1600000        60       31        26667.0     Yaxshi         Yuqori
5  Sha  2100000        87       27        24138.0     Yaxshi         Yuqori
6   Ya  1350000        49       24        27551.0      Yomon          O'rta

In [55]:
# Har bir "Sotuv_darajasi" guruhida nechta kun borligi

df["Yaxshi_kun"].value_counts()

Yaxshi_kun
Yomon     4
Yaxshi    3
Name: count, dtype: int64

# iloc va loc farqi?

* Pandasda ikkalasi ham ma’lumot tanlash uchun ishlatiladi.
  - loc  -> index/column nomi bilan => loc[0:2] (2 ham kiradi)
  - iloc -> index raqami bilan      => iloc[0:2] (2 kirmaydi)